fix #15 add composer cache to travis builds
pacifica/pacifica-search-drupal pull request #17
Opened 2017-05-23 15:59 UTC by dmlb2000

### Description

This adds a generic cache directory to travis yaml to hopefully cache the composer files dir
### Issues Resolved

#15 
### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2017-05-23 20:20 UTC, thomscode requested changes

2017-05-23 20:20 UTC, thomscode commented on travis/script.sh
> +    composer --verbose require --no-update drupal/core:8.4.x-dev drush/drush:9.0.x-dev
This line should be removed or commented as we aren't doing drupal core development

2017-05-24 13:25 UTC, dmlb2000 commented on travis/script.sh
> +    composer --verbose require --no-update drupal/core:8.4.x-dev drush/drush:9.0.x-dev
This is under the `RELEASE=dev` environment variable which isn't being set... so this is never being hit... I'd like to keep it as it's a way of getting a pre-release of drupal to test against (just in case) so I'll comment it out with the note for now

2017-05-24 14:15 UTC, dmlb2000 commented
Okay, so in the (right now) web directory where would the code you write go to perform php tests?

2017-05-24 15:15 UTC, thomscode approved these changes

2017-05-24 15:17 UTC, thomscode commented
@dmlb2000 
I submitted an "approved" review, but as I don't have write access to the repository, it's still showing as blocked.

2017-05-24 15:43 UTC, merged